"""
Generic strategy abstraction and trade signal models.
"""
from abc import ABC, abstractmethod
from enum import Enum
from typing import Dict, Any, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
import pandas as pd


class SignalAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    EXIT = "EXIT"
    HOLD = "HOLD"


class Signal(BaseModel):
    """
    Trade signal generated by a Strategy on bar completion.
    """
    action: SignalAction
    symbol: str
    timestamp: datetime
    price: float
    suggested_quantity: Optional[int] = None
    stop_loss: Optional[float] = None
    target: Optional[float] = None
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    reason: str = ""
    metadata: Dict[str, Any] = Field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract Base Class for quantitative trading strategies.
    Strategies are pure logic and have zero direct broker or execution dependencies.
    """
    name: str = "BaseStrategy"
    version: str = "1.0.0"
    description: str = ""

    def __init__(self, parameters: Optional[Dict[str, Any]] = None):
        self.parameters = parameters or {}
        self.validate_parameters()

    @abstractmethod
    def validate_parameters(self) -> None:
        """Validate parameter ranges and relationships."""
        pass

    @abstractmethod
    def on_bar(
        self,
        current_candle: pd.Series,
        historical_candles: pd.DataFrame,
        portfolio_state: Optional[Dict[str, Any]] = None
    ) -> List[Signal]:
        """
        Event-driven bar handler called on every new closed candle.
        Must NOT access future candles (avoids lookahead bias).
        """
        pass

    def get_parameter_schema(self) -> Dict[str, Any]:
        """Return schema of configurable parameters for UI rendering."""
        return {}
